version: "3"
services:
    db:
        image: mongo:4.4
        volumes:
          - ./data/db:/data/db
        expose:
          - "27017"
        ports:
        - "27017:27017"

    search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        container_name: es01
        environment:
          - node.name=es01
          - cluster.name=es-docker-cluster
          - cluster.initial_master_nodes=es01
        volumes:
          - ./data/search/data:/usr/share/elasticsearch/data
        expose:
          - "9200"
        ports:
          - "9200:9200"
