version: "3"
services:
    search_test:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        container_name: es01_test
        environment:
          - node.name=es01_test
          - cluster.name=es-docker-cluster-test
          - cluster.initial_master_nodes=es01_test
        tmpfs: /usr/share/elasticsearch/data
        expose:
          - "9200"
        ports:
          - "9200:9200"
