version: "3"
services:
    db_test:
        image: mongo:4.4
        tmpfs: /data/db/
        ports:
          - "27017:27017"

    search_test:
        image: elasticsearch:7.13
        tmpfs: /usr/share/elasticsearch/data
        ports:
          - "9200:9200"
